In [1]:
#Create a 1D array of numbers from 10 to 50.
import numpy as np
array = np.arange(10, 51)
print(array)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [4]:
#Create a 3x3 array of random numbers between 0 and 1.

array = np.random.rand(3, 3)
print(array)


[[2.64098613e-01 6.86069543e-01 8.06975182e-01]
 [8.09989365e-01 1.41663249e-01 6.26911490e-01]
 [4.36959593e-04 2.29148770e-01 6.73010054e-01]]


In [5]:
#Find the shape, size, and data type of the array you created in the previous task.

array = np.random.rand(3, 3)
shape = array.shape
size = array.size
dtype = array.dtype
print("Shape:", shape)
print("Size:", size)
print("Data type:", dtype)


Shape: (3, 3)
Size: 9
Data type: float64


In [6]:
#Add 5 to every element of a 1D array.
array = np.array([1, 2, 3, 4, 5])
add_5 = array + 5
print(add_5)


[ 6  7  8  9 10]


In [7]:
#Multiply two 2D arrays element-wise
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
result = array1 * array2
print(result)


[[ 7 16 27]
 [40 55 72]]


In [8]:
#Create a 5x5 array of integers from 1 to 25. Extract:
#The first row.
#The last column.
#A subarray of the first three rows and first two columns.
array = np.arange(1, 26).reshape(5, 5)
first_row = array[0, :]
last_column = array[:, -1]
subarray = array[:3, :2]
print("Original Array:", array)
print("First Row:", first_row)
print("Last Column:", last_column)
print("Subarray of first 3 rows and first 2 columns:", subarray)


Original Array: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
First Row: [1 2 3 4 5]
Last Column: [ 5 10 15 20 25]
Subarray of first 3 rows and first 2 columns: [[ 1  2]
 [ 6  7]
 [11 12]]


In [9]:
#Create a 10-element array of random integers between 1 and 100. Find:
#The maximum value.
#The minimum value.
#The mean and standard deviation.
array = np.random.randint(1, 101, 10)
max_value = np.max(array)
min_value = np.min(array)
mean_value = np.mean(array)
std_dev = np.std(array)
print("Array:", array)
print("Maximum Value:", max_value)
print("Minimum Value:", min_value)
print("Mean Value:", mean_value)
print("Standard Deviation:", std_dev)


Array: [24 93  9 49 25 48 50 97 25 87]
Maximum Value: 97
Minimum Value: 9
Mean Value: 50.7
Standard Deviation: 30.056779601281306


In [10]:
#Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
array = np.arange(1, 13)
matrix = array.reshape(3, 4)
print(matrix)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
#Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
matrix_ones = np.ones((3, 3))
array = np.array([1, 2, 3])
result = matrix_ones + array
print(result)


[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [12]:
#Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
array = np.random.randint(1, 51, 10)
divisible_by_5 = array[array % 5 == 0]
print("Original Array:", array)
print("Elements divisible by 5:", divisible_by_5)


Original Array: [17 27 45 31 23  6 45 19 35 25]
Elements divisible by 5: [45 45 35 25]


In [13]:
#Create two 2x2 matrices and perform matrix multiplication.
import numpy as np
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2)
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Result of Matrix Multiplication:\n", result)


Matrix 1:
 [[1 2]
 [3 4]]
Matrix 2:
 [[5 6]
 [7 8]]
Result of Matrix Multiplication:
 [[19 22]
 [43 50]]


In [14]:
#Given a 4x4 array, use fancy indexing to extract the diagonal elements.
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])
diagonal_elements = array[np.arange(4), np.arange(4)]
print("Original 4x4 Array:\n", array)
print("Diagonal Elements:", diagonal_elements)


Original 4x4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Diagonal Elements: [ 1  6 11 16]
